/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.table.DefaultTableModel;
import gestion.Gestion_clientes;
import java.util.List;
import entidades.Cliente;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class Frm_clientes extends javax.swing.JFrame {

    private Gestion_clientes gestionClientes = null;

    public Frm_clientes(Gestion_clientes gestionClientes) {
        initComponents();
        this.gestionClientes = gestionClientes;
        refreshLista(this.gestionClientes.getLista_clientes());
        // String[] datos = {"0", "adsad", "asdsa","asdsa","asdas","adas"};
        //DefaultTableModel modelo=(DefaultTableModel)jtb_listaClientes.getModel();
        //modelo.addRow(datos);
    }

    private void clearTable() {
        DefaultTableModel modelo = (DefaultTableModel) jtb_listaClientes.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void refreshLista(List lista) {
        if (lista != null) {
            clearTable();
            DefaultTableModel modelo = (DefaultTableModel) jtb_listaClientes.getModel();
            for (int i = 0; i < lista.size(); i++) {
                Cliente c_tmp = (Cliente) lista.get(i);
                String[] datos = {
                    c_tmp.getId() + "",
                    c_tmp.getNombre() + " " + c_tmp.getApaterno() + " " + c_tmp.getAmaterno(),
                    c_tmp.getTipoTXT(c_tmp.getTipo()),
                    c_tmp.getCorreo(),
                    c_tmp.getTelefono()
                };
                modelo.addRow(datos);
            }
        }
    }

    public Gestion_clientes getGestionClientes() {
        return gestionClientes;
    }

    public void setGestionClientes(Gestion_clientes gestionClientes) {
        this.gestionClientes = gestionClientes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_agregacliente = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_eliminacliente = new javax.swing.JButton();
        btn_modificacliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_listaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestió de Clientes");

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_agregacliente.setText("Agregar");
        btn_agregacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaclienteActionPerformed(evt);
            }
        });

        btn_buscar.setText("b");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminacliente.setText("Eliminar");
        btn_eliminacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminaclienteActionPerformed(evt);
            }
        });

        btn_modificacliente.setText("Modificar");
        btn_modificacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificaclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_agregacliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modificacliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminacliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_agregacliente)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_eliminacliente)
                    .addComponent(btn_modificacliente)))
        );

        jtb_listaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo", "Correo", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jtb_listaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
     
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        refreshLista(this.gestionClientes.getLista_clientes());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_agregaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaclienteActionPerformed
        new Frm_addUpdCliente(this).setVisible(true);
    }//GEN-LAST:event_btn_agregaclienteActionPerformed

    private void btn_eliminaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminaclienteActionPerformed
         int filaSelecccionada=this.jtb_listaClientes.getSelectedRow();
        if (filaSelecccionada!=-1) {
            int idClienteaBuscar=Integer.parseInt((String)jtb_listaClientes.getValueAt(filaSelecccionada, 0));
            Cliente clienteAEliminar=gestionClientes.buscar(idClienteaBuscar);
            gestionClientes.elimina(clienteAEliminar);
            refreshLista(this.gestionClientes.getLista_clientes());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona un cliente para Eliminar", "No has seleccionado un cliente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminaclienteActionPerformed

   
    
    private void btn_modificaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificaclienteActionPerformed
        int filaSelecccionada=this.jtb_listaClientes.getSelectedRow();
        if (filaSelecccionada!=-1) {
            System.out.println(jtb_listaClientes.getValueAt(filaSelecccionada, 0));
             int idClienteaBuscar=Integer.parseInt((String)jtb_listaClientes.getValueAt(filaSelecccionada, 0));
            Cliente clienteAmodificar=gestionClientes.buscar(idClienteaBuscar);
            new Frm_addUpdCliente(this,clienteAmodificar).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona un cliente para modificar", "No has seleccionado un cliente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_modificaclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregacliente;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminacliente;
    private javax.swing.JButton btn_modificacliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtb_listaClientes;
    // End of variables declaration//GEN-END:variables
}
